name: Ejecutar Scraping con Playwright

on:
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  scraping_job:
    runs-on: ubuntu-latest

    # Añadimos permisos de escritura para que el bot pueda subir archivos
    permissions:
      contents: write

    steps:
    - name: 📥 Descargar mi código
      uses: actions/checkout@v4

    - name: 🐍 Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 🛠️ Instalar Playwright y dependencias
      run: |
        pip install playwright
        playwright install chromium --with-deps

    - name: 🚀 Ejecutar Extractor de Imágenes
      # Cambiamos el comando para que ejecute el nuevo script de imágenes
      run: python PlayWright/extractor_imagenes.py

    - name: 📤 Subir cambios al Repositorio
      run: |
        # Configuramos la identidad del bot (ShadowRoot Cloud)
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Agregamos la imagen descargada
        git add archivos_extraidos/*.jpg
        
        # Hacemos el commit. Si no hay cambios, no da error.
        git commit -m "feat: imagen capturada por Playwright [skip ci]" || echo "No hay cambios para subir"
        
        # Mandamos los archivos de vuelta a tu GitHub
        git push

